<?xml version="1.0" encoding="utf-8"?>
<SyntaxDefinition name="QDockerfile" extensions=".dockerfile" xmlns="http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008">
  <Color name="Comment" foreground="#6A9955" fontStyle="italic"/>
  <Color name="String" foreground="#CE9178"/>
  <Color name="Keyword" foreground="#569CD6"/>
  <Color name="Variable" foreground="#9CDCFE"/>
  <Color name="Number" foreground="#B5CEA8"/>
  <RuleSet>
    <Span color="Comment" begin="^\s*#" />
    <Span color="String"><Begin>"</Begin><End>"</End><RuleSet><Span begin="\\" end="."/></RuleSet></Span>
    <Span color="String"><Begin>'</Begin><End>'</End></Span>
    <Rule color="Variable">\$\{[^}]*\}|\$[A-Za-z_]\w*</Rule>
    <Rule color="Keyword">(?i)^\s*(FROM|RUN|CMD|LABEL|MAINTAINER|EXPOSE|ENV|ADD|COPY|ENTRYPOINT|VOLUME|USER|WORKDIR|ARG|ONBUILD|STOPSIGNAL|HEALTHCHECK|SHELL|AS)\b</Rule>
    <Rule color="Number">\b\d+\b</Rule>
  </RuleSet>
</SyntaxDefinition>
